### PR TITLE
Correctly handle deletions from queues

### LINKED ISSUE #59: Deletion of CRDs isn't working as expected
For some reason, on a CRD delete, this is triggered, meaning the factory can't find the object. An example of the error I get is as follows:

```
time="2018-05-30 18:51:03.41696" level=info msg="Read item 'default/yogi-bear' off workqueue. Processing..." loc="crd/crd_queue.go(67)" logger=netmeshcrd
time="2018-05-30 18:51:03.41759" level=info msg="Dequeuing interface of type networkservices" loc="crd/crd_queue.go(70)" logger=netmeshcrd
ERROR: logging before flag.Parse: E0530 18:51:03.417636       1 crd_queue.go:74] error getting object 'default/yogi-bear' from api: networkservice.networkservicemesh.io "yogi-bear" not found
```

### PR DESCRIPTION
**Pull request by mestery**
This commit closes #59.

This commit modifies how we process delete events from the queues.
Specifically, it does a few things:

* Saves off informers as a part of the CRD Plugin for use in queue
  processing.
* Uses GetByKey() to get an object instead of directly using the sharedfactory
  Lister function.
* GetByKey() allows us to determine if an item existed already, thus signaling
  a deletion.
* Retries SplitMetaNamespaceKey() and GetByKey() errors up to five times to
  handle transient errors.

With this change, the CRD code is now much more robust.

Signed-off-by: Kyle Mestery <mestery@mestery.com>

### CODE REVIEW

**Comment by sbezverk** [comment]
@mestery I was looking at the code and imho handling errors produced on lines 58 and 81 with retries is not necessary because these errors are not transient in nature. line 58 error would be triggered only when strKey is "" and same thing for line 81, I am not sure if there is any chances that these would recover. I might be wrong though.

**Comment by mestery** [comment]
Thanks for the review @sbezverk! The retry around line 58 I would be willing to remove, but I think the one around line 81 is still necessary and I'd like to leave it in there.

File: plugins/crd/crd_queue.go [hunk 1]
```diff
@@ -49,39 +53,53 @@ func networkserviceWork(plugin *Plugin) {
...
 
 			if err != nil {
+				// This is a soft-error, retry up to QUEUE_RETRY_COUNT times
 				plugin.Log.Errorf("Error splitting meta namespace key into parts: %s", err.Error())
-				runtime.HandleError(fmt.Errorf("Error splitting meta namespace key into parts: %s", err.Error()))
-				// This is a soft-error, we merely want to forget it and mark it done on the queue
-				queueNS.Forget(key)
+				if err != nil {
+					if queueNS.NumRequeues(key) < QUEUE_RETRY_COUNT {
+						plugin.Log.Errorf("Error processing item with key %s, error %v", key, err)
```
Comment (prateekgogia) [inline plugins/crd/crd_queue.go]: Is there a reason we need to retry when `SplitMetaNamespaceKey` method returns an error, because all this method is doing is a key split and everytime we retry `key` remains the same, it will keep failing. Unless I am missing something here.

Comment (mestery) [reply plugins/crd/crd_queue.go]: This is a valid point, I'll re-spin removing the retry here.

File: plugins/crd/crd_queue.go [hunk 2]
```diff
@@ -49,39 +53,53 @@ func networkserviceWork(plugin *Plugin) {
...
+			// GetByKey() we are able to determine if the item exists, and thus if it was
+			// added or deleted from the queue, and process appropriately
+			item, exists, err := plugin.informerNS.GetIndexer().GetByKey(strKey)
 
 			if err != nil {
-				plugin.Log.Errorf("Error getting object '%s/%s' from api: %s", namespace, name, err.Error())
-				runtime.HandleError(fmt.Errorf("Error getting object '%s/%s' from api: %s", namespace, name, err.Error()))
-				// This is a hard-error, we'll raise the flag so the plugin catches this and shuts down
-				queueNS.Forget(key)
-				plugin.queueError <- true
```
Comment (prateekgogia) [inline plugins/crd/crd_queue.go]: Also, since we are removing this `queueError` functionality here in this PR. There is a goroutine running listening on this `queueError` channel [here](https://github.com/ligato/networkservicemesh/blob/master/plugins/crd/plugin_impl_crd.go#L423) but no one is sending anything to this channel. 

May be that clean up can be done later after this gets in, if we intend to not use it.

File: plugins/crd/crd_queue.go [hunk 3]
```diff
@@ -49,39 +53,53 @@ func networkserviceWork(plugin *Plugin) {
...
 			namespace, name, err := cache.SplitMetaNamespaceKey(strKey)
 
 			if err != nil {
+				// This is a soft-error, retry up to QUEUE_RETRY_COUNT times
 				plugin.Log.Errorf("Error splitting meta namespace key into parts: %s", err.Error())
-				runtime.HandleError(fmt.Errorf("Error splitting meta namespace key into parts: %s", err.Error()))
-				// This is a soft-error, we merely want to forget it and mark it done on the queue
-				queueNS.Forget(key)
+				if err != nil {
+					if queueNS.NumRequeues(key) < QUEUE_RETRY_COUNT {
```
Comment (fkautz) [inline plugins/crd/crd_queue.go]: Why would this condition be an error if it returns less than the retry count? The documentation reads as follows:

```go
	// NumRequeues returns back how many failures the item has had
	NumRequeues(item interface{}) int
```

File: plugins/crd/crd_queue.go [hunk 4]
```diff
@@ -49,39 +53,53 @@ func networkserviceWork(plugin *Plugin) {
...
 			}
 
 			plugin.Log.Infof("Read item '%s/%s' off workqueue. Processing...", namespace, name)
 
-			// Retrieve the latest version in the cache of this alert
-			obj, err = plugin.sharedFactoryNS.Networkservice().V1().NetworkServices().Lister().NetworkServices(namespace).Get(name)
+			// Retrieve the latest version in the cache of this NetworkService. By using
+			// GetByKey() we are able to determine if the item exists, and thus if it was
+			// added or deleted from the queue, and process appropriately
+			item, exists, err := plugin.informerNS.GetIndexer().GetByKey(strKey)
```
Comment (fkautz) [inline plugins/crd/crd_queue.go]: What kind of cache is this? Is it possible for the key to be evicted while the object may actually exist?

File: plugins/crd/crd_queue.go [hunk 5]
```diff
@@ -49,39 +53,53 @@ func networkserviceWork(plugin *Plugin) {
...
 
 			if err != nil {
-				plugin.Log.Errorf("Error getting object '%s/%s' from api: %s", namespace, name, err.Error())
-				runtime.HandleError(fmt.Errorf("Error getting object '%s/%s' from api: %s", namespace, name, err.Error()))
-				// This is a hard-error, we'll raise the flag so the plugin catches this and shuts down
-				queueNS.Forget(key)
-				plugin.queueError <- true
-				return
+				if queueNS.NumRequeues(key) < QUEUE_RETRY_COUNT {
```
Comment (fkautz) [inline plugins/crd/crd_queue.go]: Same question as above about NumRequeues()

File: plugins/crd/crd_queue.go [hunk 6]
```diff
@@ -114,6 +132,7 @@ func networkservicechannelWork(plugin *Plugin) {
 
 		// If the queue has been shut down, we should exit the work queue here
 		if shutdown {
+			plugin.Log.Error("shutdown signaled, closing stopChNSC")
 			plugin.stopChNSC <- struct{}{}
```
Comment (fkautz) [inline plugins/crd/crd_queue.go]: This takes a struct{} but a struct{}{} is passed in. Any reason for this?

File: plugins/crd/crd_queue.go [hunk 7]
```diff
@@ -130,39 +149,53 @@ func networkservicechannelWork(plugin *Plugin) {
...
+			item, exists, err := plugin.informerNSC.GetIndexer().GetByKey(strKey)
 
 			if err != nil {
-				plugin.Log.Errorf("Error getting object '%s/%s' from api: %s", namespace, name, err.Error())
-				runtime.HandleError(fmt.Errorf("Error getting object '%s/%s' from api: %s", namespace, name, err.Error()))
-				// This is a hard-error, we'll raise the flag so the plugin catches this and shuts down
-				queueNSC.Forget(key)
-				plugin.queueError <- true
-				return
+				if queueNSC.NumRequeues(key) < QUEUE_RETRY_COUNT {
```
Comment (fkautz) [inline plugins/crd/crd_queue.go]: Most of this code looks like it is repeated, can it be refactored to a single method?

File: plugins/crd/crd_queue.go [hunk 8]
```diff
@@ -49,39 +53,53 @@ func networkserviceWork(plugin *Plugin) {
...
 			// Attempt to split the 'key' into namespace and object name
 			namespace, name, err := cache.SplitMetaNamespaceKey(strKey)
 
 			if err != nil {
+				// This is a soft-error, retry up to QUEUE_RETRY_COUNT times
 				plugin.Log.Errorf("Error splitting meta namespace key into parts: %s", err.Error())
-				runtime.HandleError(fmt.Errorf("Error splitting meta namespace key into parts: %s", err.Error()))
-				// This is a soft-error, we merely want to forget it and mark it done on the queue
-				queueNS.Forget(key)
+				if err != nil {
```
[the remark this answers is not in the document]
Comment (mestery) [reply plugins/crd/crd_queue.go]: I cleaned this up while addressing one of @prateekgogia's comments, but did not push the new commit yet, so this will be cleaned up when I do that this morning.

File: plugins/crd/crd_queue.go (hunk 3 above)
Comment (mestery) [reply plugins/crd/crd_queue.go]: The idea is we're flagging the fact it's an error, and then re-queueing the item. I'll change the error message in this particular case.

File: plugins/crd/crd_queue.go (hunk 4 above)
Comment (mestery) [reply plugins/crd/crd_queue.go]: These are SharedIndexInformer caches, see here [1] and here [2]. It should not be possible for the key to evicted while the object actually exists either, unless there is an error in the processing logic.

[1] https://github.com/ligato/networkservicemesh/blob/master/plugins/crd/plugin_impl_crd.go#L68
[2] https://github.com/ligato/networkservicemesh/blob/master/plugins/crd/plugin_impl_crd.go#L251

File: plugins/crd/crd_queue.go (hunk 2 above)
Comment (mestery) [reply plugins/crd/crd_queue.go]: Good catch, I will remove this.

File: plugins/crd/crd_queue.go (hunk 6 above)
Comment (mestery) [reply plugins/crd/crd_queue.go]: If I try to pass in a `struct{}` I get the error:

`type struct{} is not an expression`

File: plugins/crd/crd_queue.go (hunk 7 above)
Comment (mestery) [reply plugins/crd/crd_queue.go]: I agree that appears to be the case. Would it be ok to file an issue and refactor it as a separate commit?

File: plugins/crd/crd_queue.go (hunk 6 above)
Comment (mestery) [reply plugins/crd/crd_queue.go]: Now that you mention this, I do recall this came up in the code walkthrough we did a few weeks back. But lets open an issue to track changing this.
